name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: IMBPlexSans
      fonts:
        - asset: fonts/IBMPlexSans/IBMPlexSans-Regular.ttf
    - family: Grenze
      fonts:
        - asset: fonts/Grenze/Grenze-Regular.ttf
    - family: SourceSans
      fonts:
        - asset: fonts/SourceSans/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSans/SourceSansPro-Bold.ttf